export const siteConfig = {
  businessInfo: {
    shortName: 'רועי אילון',
    category: 'עיצוב שיער',
    heroEyebrow: 'סטודיו פרימיום לעיצוב שיער',
    heroSubtitle: 'לא רודפים אחרי טרנדים. יוצרים שיער שמספר את הסיפור שלך.',
    footerTagline: 'סטודיו לעיצוב שיער בלב תל אביב. צבע, בליאז׳, החלקות ותספורות — מאז 2012.',
    foundedYear: 2012,
    phone: '03-1234567',
    address: 'שינקין 22, תל אביב',
    mapQuery: 'Sheinkin Street Tel Aviv',
    hours: [
      { day: 'ראשון – חמישי', time: '09:00 – 21:00' },
      { day: 'שישי', time: '08:00 – 15:00' },
      { day: 'שבת', time: 'סגור' },
    ],
    stats: [
      { num: '15+', label: 'שנות ניסיון' },
      { num: '500+', label: 'לקוחות מרוצים' },
      { num: '4.9★', label: 'דירוג גוגל' },
    ],
    socials: [
      { label: 'אינסטגרם', href: '#' },
      { label: 'פייסבוק', href: '#' },
      { label: 'וואטסאפ', href: '#' },
    ],
  },

  servicesData: [
    {
      id: 'color',
      title: 'צבע שיער, גוונים ובליאז׳',
      price: '280₪',
      duration: '90 דק׳',
      desc: 'מגוון עד בליאז׳ טבעי - כל גוון נבנה במיוחד בשבילך, לפי גוון העור ומה שבא לך להרגיש.',
      audience: 'women',
      barberId: 'michal',
    },
    {
      id: 'keratin',
      title: 'החלקות וקרטין',
      price: '450₪',
      duration: '120 דק׳',
      desc: 'טיפול שמחזיר לשיער חלקות, ברק ושליטה - בלי לוותר על התנועה הטבעית שלו.',
      audience: 'women',
      barberId: 'shiran',
    },
    {
      id: 'womens-cut',
      title: 'תספורות ועיצוב נשי',
      price: '150₪',
      duration: '50 דק׳',
      desc: 'תספורת שמתחילה בשיחה על מה שאת רוצה, וממשיכה בגזירה מדויקת לפי מבנה הפנים.',
      audience: 'women',
      barberId: 'roi',
    },
    {
      id: 'blowdry',
      title: 'פן ועיצוב לאירועים',
      price: '120₪',
      duration: '45 דק׳',
      desc: 'תמיד מגיע בול בזמן. פן חלק ליומיום, או עיצוב מיוחד לאירוע שלא שוכחים.',
      audience: 'women',
      barberId: 'roi',
    },
    {
      id: 'extensions',
      title: 'תוספות שיער',
      price: '650₪',
      duration: '150 דק׳',
      desc: 'אורך ונפח שנראים אמיתיים לגמרי. מתאימים לצבע ולמרקם השיער שלך אחד לאחד.',
      audience: 'women',
      barberId: 'michal',
    },
    {
      id: 'mens-cut',
      title: 'תספורת גברים',
      price: '110₪',
      duration: '35 דק׳',
      desc: 'תספורת נקייה ומדויקת, עם גימור על קו השיער שנשאר חד גם שבועות אחרי.',
      audience: 'men',
      barberId: 'itay',
    },
  ],

  staffData: [
    { id: 'roi', name: 'רועי אילון', role: 'מייסד ומעצב שיער ראשי' },
    { id: 'michal', name: 'מיכל בר', role: 'מומחית צבע ובליאז׳' },
    { id: 'shiran', name: 'שירן כהן', role: 'מומחית החלקות וקרטין' },
    { id: 'itay', name: 'איתי גולן', role: 'תספורות גברים' },
  ],

  theme: {
    colors: {
      charcoal: '#2b221d',
      charcoalLight: '#3a2e27',
      cream: '#f8f1e7',
      creamDim: '#ece0d0',
      copper: '#c9a48c',
      copperLight: '#d9bfa9',
      gold: '#d9bd86',
      burgundy: '#c97c67',
      stone: '#9c8f82',
    },
    fonts: {
      display: "'Frank Ruhl Libre', serif",
      body: "'Assistant', sans-serif",
    },
    heroImage: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1920&h=1280&fit=crop&auto=format&q=80',
    heroImageAlt: 'פנים הסטודיו - כיסאות עיצוב שיער וסביבת עבודה',
  },
}
