export const siteConfig = {
  businessInfo: {
    shortName: 'שורש',
    category: 'סלון שיער אורגני',
    heroEyebrow: 'סלון שיער אורגני בלב תל אביב',
    heroSubtitle: 'צבע מהצומח, טיפוח שמכבד את השיער שלך - ותוצאה שרואים ומרגישים.',
    footerTagline: 'סלון שיער אורגני בלב תל אביב. תספורות, צביעה טבעית וטיפוחי שיער — מאז 2015.',
    foundedYear: 2015,
    phone: '03-5551234',
    address: 'דיזנגוף 100, תל אביב',
    mapQuery: 'Dizengoff Street Tel Aviv',
    hours: [
      { day: 'ראשון – חמישי', time: '09:30 – 20:00' },
      { day: 'שישי', time: '08:30 – 15:00' },
      { day: 'שבת', time: 'סגור' },
    ],
    stats: [
      { num: '10+', label: 'שנות ניסיון' },
      { num: '800+', label: 'לקוחות מרוצים' },
      { num: '4.9★', label: 'דירוג גוגל' },
    ],
    socials: [
      { label: 'אינסטגרם', href: '#' },
      { label: 'פייסבוק', href: '#' },
      { label: 'וואטסאפ', href: '#' },
    ],
  },

  nav: {
    ariaLabel: 'ניווט ראשי',
    links: [
      { href: '#services', label: 'שירותים' },
      { href: '#gallery', label: 'עבודות' },
      { href: '#testimonials', label: 'לקוחות ממליצות' },
      { href: '#contact', label: 'צור קשר' },
    ],
    bookCta: 'קבעו תור',
    menuOpenLabel: 'פתיחת תפריט',
    menuCloseLabel: 'סגירת תפריט',
  },

  content: {
    skipToMain: 'דלגו לתוכן הראשי',
    floatingCta: 'קביעת תור',
    hero: {
      ariaLabel: 'כותרת ראשית',
      ctaBook: 'קביעת תור',
      ctaPrices: 'מחירון שירותים',
    },
    team: {
      eyebrow: 'הצוות שלנו',
      title: 'מי מטפל/ת בך',
      ariaLabel: 'בחירת מטפל/ת',
    },
    services: {
      eyebrow: 'מה אנחנו מציעים',
      title: 'מחירון שירותים',
      filterLabel: 'סינון לפי קהל יעד',
      filterAll: 'כל הטיפולים',
      filterMen: 'טיפולים לגברים',
    },
    serviceCard: {
      bookLabel: 'להזמנה',
      badges: { women: 'נשים', men: 'גברים' },
    },
    gallery: {
      eyebrow: 'תיק עבודות',
      title: 'כל תמונה מדברת בעד עצמה',
    },
    about: {
      eyebrow: 'הסיפור שלנו',
      title: 'כל שיער מספר סיפור אחר',
      paragraphs: [
        'מה שהתחיל ב־{year} כחדר קטן בשינקין, הפך לכתובת שאליה מגיעים כשרוצים שינוי אמיתי - גוון חדש, אורך אחר, או פשוט מישהי שבאמת מקשיבה לפני שהיא נוגעת בשיער שלך. בלי פשרות על התוצאה, בלי חיפזון בדרך אליה.',
        'הצוות שלנו מתמחה בצבע ובליאז׳, החלקות, ותספורות שנבנות לפי מבנה הפנים והאישיות שלך - לא לפי תמונה שהבאת מאינסטגרם.',
      ],
      foundedNote: 'השנה בה הכל התחיל',
    },
    testimonials: {
      eyebrow: 'לקוחות ממליצות',
      title: 'מה שאומרים עלינו',
      prevLabel: 'ביקורת קודמת',
      nextLabel: 'ביקורת הבאה',
    },
    contact: {
      eyebrow: 'בואו לבקר',
      title: 'יש שאלה? בואו נדבר',
      form: {
        nameLabel: 'שם',
        namePlaceholder: 'השם שלך',
        nameError: 'נא למלא שם',
        contactLabel: 'טלפון או אימייל',
        contactPlaceholder: '0501234567 או you@example.com',
        contactError: 'נא להזין טלפון או אימייל תקין',
        messageLabel: 'הודעה',
        messagePlaceholder: 'איך נוכל לעזור?',
        messageError: 'נא לכתוב הודעה קצרה',
        submitLabel: 'שליחת הודעה',
        sentTitle: 'ההודעה נשלחה',
        sentBody: 'נחזור אליכם בהקדם. תודה שפניתם אלינו.',
        sendAnotherLabel: 'שליחת הודעה נוספת',
      },
      info: {
        mapTitle: 'מיקום הסטודיו על מפה',
        addressLabel: 'כתובת',
        phoneLabel: 'טלפון',
        hoursLabel: 'שעות פתיחה',
      },
    },
    booking: {
      title: 'קביעת תור',
      doneTitle: 'התור נקבע',
      backLabel: 'חזרה',
      closeLabel: 'סגירה',
      serviceStepLabel: 'בחירת שירות',
      staffStepLabel: 'בחירת ספר/ית',
      dateStepLabel: 'בחירת תאריך',
      timeStepLabel: 'בחירת שעה',
      todayLabel: 'היום',
      bookedLabel: 'תפוס',
      pickDateHint: 'בחרו תאריך כדי לראות שעות פנויות',
      nameLabel: 'שם מלא',
      namePlaceholder: 'ישראל ישראלי',
      phoneLabel: 'טלפון נייד',
      phonePlaceholder: '0501234567',
      phoneError: 'מספר טלפון לא תקין — נסו לדוגמה 0501234567',
      consentLabel: 'מעדכנים אותי במבצעים ותזכורות לתור',
      summaryTitle: 'סיכום ההזמנה',
      nextLabel: 'המשך',
      confirmLabel: 'אישור הזמנה',
      dateTimeSummary: 'יום {day}, {date} ל{month} בשעה {time}',
      confirmation: {
        greeting: 'מחכים לך, {name}',
        summary: '{service} עם {barber} — יום {day}, {date} ל{month} בשעה {time}.',
        demoNote: 'זהו דמו — לא נשלח אישור אמיתי.',
        anotherLabel: 'תור נוסף',
        closeLabel: 'סגירה',
      },
    },
    footer: {
      quickNavTitle: 'ניווט מהיר',
      bookingLinkLabel: 'הזמנת תור',
      socialTitle: 'עקבו אחרינו',
      rightsNote: 'כל הזכויות שמורות.',
      demoNote: 'אתר דמו לצורכי הדגמה בלבד',
    },
  },

  servicesData: [
    {
      id: 'haircut',
      title: 'תספורת ועיצוב',
      price: '180₪',
      duration: '50 דק׳',
      desc: 'תספורת שמתחילה בשיחה על מה שאת רוצה, וממשיכה בגזירה מדויקת לפי מבנה הפנים.',
      audience: 'women',
      barberId: 'mai',
    },
    {
      id: 'henna-color',
      title: 'צביעה טבעית בחינה',
      price: '260₪',
      duration: '90 דק׳',
      desc: 'צבע מהצומח, בלי אמוניה ובלי כימיקלים אגרסיביים - גוון עשיר שמזין את השיער במקום לפגוע בו.',
      audience: 'women',
      barberId: 'roni',
    },
    {
      id: 'oil-treatment',
      title: 'טיפול שיער בשמנים טבעיים',
      price: '220₪',
      duration: '60 דק׳',
      desc: 'שמן ארגן, קוקוס וקיק שחודרים עמוק לסיבי השיער - ברק וגמישות שמחזיקים מעמד.',
      audience: 'women',
      barberId: 'liron',
    },
    {
      id: 'blowdry',
      title: 'פן ועיצוב',
      price: '140₪',
      duration: '45 דק׳',
      desc: 'פן חלק ליומיום, או עיצוב מיוחד לאירוע שלא שוכחים.',
      audience: 'women',
      barberId: 'mai',
    },
    {
      id: 'updo',
      title: 'עיצוב תסרוקות לאירועים',
      price: '280₪',
      duration: '75 דק׳',
      desc: 'תסרוקת שמחזיקה כל הערב, מותאמת בול לשמלה ולאירוע שלך.',
      audience: 'women',
      barberId: 'liron',
    },
    {
      id: 'mens-cut',
      title: 'תספורת גברים קלאסית',
      price: '120₪',
      duration: '40 דק׳',
      desc: 'תספורת נקייה ומדויקת, עם גימור על קו השיער שנשאר חד גם שבועות אחרי.',
      audience: 'men',
      barberId: 'daniel',
    },
    {
      id: 'mens-beard-oil',
      title: 'טיפוח זקן בשמנים טבעיים',
      price: '100₪',
      duration: '30 דק׳',
      desc: 'שמנים טבעיים שמרככים את הזקן ומטפחים את העור מתחתיו - בלי גירויים.',
      audience: 'men',
      barberId: 'daniel',
    },
  ],

  staffData: [
    { id: 'mai', name: 'מאי שגיא', role: 'מייסדת ומעצבת שיער ראשית' },
    { id: 'roni', name: 'רוני אבידן', role: 'מומחית צבע טבעי וחינה' },
    { id: 'liron', name: 'לירון כץ', role: 'מומחית טיפולי שיער ושמנים' },
    { id: 'daniel', name: 'דניאל וקנין', role: 'מטפל גברים' },
  ],

  theme: {
    colors: {
      ink: '#3f4438',
      inkLight: '#4c5142',
      surface: '#faf6ec',
      surfaceDim: '#f1e8d6',
      primary: '#c98868',
      accent: '#5c6b42',
      muted: '#8b8272',
    },
    fonts: {
      display: "'David Libre', serif",
      body: "'Assistant', sans-serif",
    },
    heroImage: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1920&h=1280&fit=crop&auto=format&q=80',
    heroImageAlt: 'פנים סלון השיער - חלל חם ונעים',
  },
}

/** Fill {placeholder} slots in a config template string. */
export function fmt(template, vars = {}) {
  return template.replace(/\{(\w+)\}/g, (match, key) => (vars[key] ?? match))
}
