export const siteConfig = {
  businessInfo: {
    shortName: 'שורש',
    category: 'סלון שיער אורגני',
    heroEyebrow: 'סלון שיער אורגני בלב תל אביב',
    heroSubtitle: 'צבע מהצומח, טיפוח שמכבד את השיער שלך - ותוצאה שרואים ומרגישים.',
    footerTagline: 'סלון שיער אורגני בלב תל אביב. תספורות, צביעה טבעית וטיפוחי שיער — מאז 2015.',
    foundedYear: 2015,
    phone: '03-5551234',
    address: 'דיזנגוף 100, תל אביב',
    mapQuery: 'Dizengoff Street Tel Aviv',
    hours: [
      { day: 'ראשון – חמישי', time: '09:30 – 20:00' },
      { day: 'שישי', time: '08:30 – 15:00' },
      { day: 'שבת', time: 'סגור' },
    ],
    stats: [
      { num: '10+', label: 'שנות ניסיון' },
      { num: '800+', label: 'לקוחות מרוצים' },
      { num: '4.9★', label: 'דירוג גוגל' },
    ],
    socials: [
      { label: 'אינסטגרם', href: '#' },
      { label: 'פייסבוק', href: '#' },
      { label: 'וואטסאפ', href: '#' },
    ],
  },

  servicesData: [
    {
      id: 'haircut',
      title: 'תספורת ועיצוב',
      price: '180₪',
      duration: '50 דק׳',
      desc: 'תספורת שמתחילה בשיחה על מה שאת רוצה, וממשיכה בגזירה מדויקת לפי מבנה הפנים.',
      audience: 'women',
      barberId: 'mai',
    },
    {
      id: 'henna-color',
      title: 'צביעה טבעית בחינה',
      price: '260₪',
      duration: '90 דק׳',
      desc: 'צבע מהצומח, בלי אמוניה ובלי כימיקלים אגרסיביים - גוון עשיר שמזין את השיער במקום לפגוע בו.',
      audience: 'women',
      barberId: 'roni',
    },
    {
      id: 'oil-treatment',
      title: 'טיפול שיער בשמנים טבעיים',
      price: '220₪',
      duration: '60 דק׳',
      desc: 'שמן ארגן, קוקוס וקיק שחודרים עמוק לסיבי השיער - ברק וגמישות שמחזיקים מעמד.',
      audience: 'women',
      barberId: 'liron',
    },
    {
      id: 'blowdry',
      title: 'פן ועיצוב',
      price: '140₪',
      duration: '45 דק׳',
      desc: 'פן חלק ליומיום, או עיצוב מיוחד לאירוע שלא שוכחים.',
      audience: 'women',
      barberId: 'mai',
    },
    {
      id: 'updo',
      title: 'עיצוב תסרוקות לאירועים',
      price: '280₪',
      duration: '75 דק׳',
      desc: 'תסרוקת שמחזיקה כל הערב, מותאמת בול לשמלה ולאירוע שלך.',
      audience: 'women',
      barberId: 'liron',
    },
    {
      id: 'mens-cut',
      title: 'תספורת גברים קלאסית',
      price: '120₪',
      duration: '40 דק׳',
      desc: 'תספורת נקייה ומדויקת, עם גימור על קו השיער שנשאר חד גם שבועות אחרי.',
      audience: 'men',
      barberId: 'daniel',
    },
    {
      id: 'mens-beard-oil',
      title: 'טיפוח זקן בשמנים טבעיים',
      price: '100₪',
      duration: '30 דק׳',
      desc: 'שמנים טבעיים שמרככים את הזקן ומטפחים את העור מתחתיו - בלי גירויים.',
      audience: 'men',
      barberId: 'daniel',
    },
  ],

  staffData: [
    { id: 'mai', name: 'מאי שגיא', role: 'מייסדת ומעצבת שיער ראשית' },
    { id: 'roni', name: 'רוני אבידן', role: 'מומחית צבע טבעי וחינה' },
    { id: 'liron', name: 'לירון כץ', role: 'מומחית טיפולי שיער ושמנים' },
    { id: 'daniel', name: 'דניאל וקנין', role: 'מטפל גברים' },
  ],

  theme: {
    colors: {
      charcoal: '#3f4438',
      charcoalLight: '#4c5142',
      cream: '#faf6ec',
      creamDim: '#f1e8d6',
      copper: '#c3a78c',
      copperLight: '#d8c7b0',
      gold: '#c98868',
      burgundy: '#5c6b42',
      stone: '#8b8272',
    },
    fonts: {
      display: "'David Libre', serif",
      body: "'Assistant', sans-serif",
    },
    heroImage: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1920&h=1280&fit=crop&auto=format&q=80',
    heroImageAlt: 'פנים סלון השיער - חלל חם ונעים',
  },
}
